### ISSUE TITLE
error in seed-voicecard install : Error! Bad return status for module build on kernel: 3.6-trunk-rpi (armv6l)

### ISSUE THREAD

**Issue by cogmeta** [respeaker/seeed-voicecard#52] opened 2018-03-29 11:37 UTC
------------------------------
Deleting module version: 0.3
completely from the DKMS tree.
------------------------------
Done.

Creating symlink /var/lib/dkms/seeed-voicecard/0.3/source ->
                 /usr/src/seeed-voicecard-0.3

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....(bad exit status: 2)
make -j1 KERNELRELEASE=3.6-trunk-rpi -C /lib/modules/3.6-trunk-rpi/build M=/var/lib/dkms/seeed-voicecard/0.3/build.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 3.6-trunk-rpi (armv6l)
Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area.....
make -j1 KERNELRELEASE=4.14.30+ -C /lib/modules/4.14.30+/build M=/var/lib/dkms/seeed-voicecard/0.3/build..........^Ap........(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.14.30+ (armv6l)
Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area.....
make -j1 KERNELRELEASE=4.14.30-v7+ -C /lib/modules/4.14.30-v7+/build M=/var/lib/dkms/seeed-voicecard/0.3/build..................(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.14.30-v7+ (armv6l)
Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.
mkdir: cannot create directory ‘/etc/voicecard’: File exists
------------------------------------------------------
Please reboot your raspberry pi to apply all settings
Enjoy!
------------------------------------------------------

$lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch

**Comment by Pillar1989** [comment] 2018-03-30 01:49
Duplicate of #48

**Closed by Pillar1989** 2018-03-30 01:49 UTC
