### ISSUE TITLE
Error! There are no instances of module: seeed-voicecard 

### ISSUE THREAD

**Issue by Fibo27** [respeaker/seeed-voicecard#161] opened 2019-05-20 15:58 UTC
Hello i have recently purchased the 6 Mic Circular Array for RPi and was following the Wiki instructions. I have had exactly similar issues like #100. 

My kernel build is shown in the below log:
Linux raspberrypi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux

My question: is the above kernel build supporting the product?

The below logs is also shown for your reference:

Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
12 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
raspberrypi-kernel is already the newest version (1.20190517-1).
raspberrypi-kernel-headers is already the newest version (1.20190517-1).
The following packages were automatically installed and are no longer required:
  realpath vlc-plugin-notify vlc-plugin-samba vlc-plugin-video-splitter
  vlc-plugin-visualization
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dkms is already the newest version (2.3-2).
git is already the newest version (1:2.11.0-3+deb9u4).
i2c-tools is already the newest version (3.1.2-3).
libasound2-plugins is already the newest version (1.1.1-1).
The following packages were automatically installed and are no longer required:
  realpath vlc-plugin-notify vlc-plugin-samba vlc-plugin-video-splitter
  vlc-plugin-visualization
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.

-------- Uninstall Beginning --------
Module:  seeed-voicecard
Version: 0.3
Kernel:  4.19.42+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

snd-soc-wm8960.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.42+/kernel/sound/soc/codecs/
 - Original module
   - Archived original module found in the DKMS tree
   - Moving it to: /lib/modules/4.19.42+/kernel/sound/soc/codecs/

snd-soc-ac108.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.42+/kernel/sound/soc/codecs/
 - Original module
   - Archived original module found in the DKMS tree
   - Moving it to: /lib/modules/4.19.42+/kernel/sound/soc/codecs/

snd-soc-seeed-voicecard.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.42+/kernel/sound/soc/bcm/
 - Original module
   - Archived original module found in the DKMS tree
   - Moving it to: /lib/modules/4.19.42+/kernel/sound/soc/bcm/
depmod....

Removing original_module from DKMS tree for kernel 4.19.42+ (armv7l)

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  seeed-voicecard
Version: 0.3
Kernel:  4.19.42-v7+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

snd-soc-wm8960.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.42-v7+/kernel/sound/soc/codecs/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

snd-soc-ac108.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.42-v7+/kernel/sound/soc/codecs/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

snd-soc-seeed-voicecard.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.42-v7+/kernel/sound/soc/bcm/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod....

DKMS: uninstall completed.

------------------------------
Deleting module version: 0.3
completely from the DKMS tree.
------------------------------
Done.

Creating symlink /var/lib/dkms/seeed-voicecard/0.3/source ->
                 /usr/src/seeed-voicecard-0.3

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=4.19.42+ -C /lib/modules/4.19.42+/build M=/var/lib/dkms/seeed-voicecard/0.3/build.....
cleaning build area...

DKMS: build completed.

snd-soc-wm8960:
Running module version sanity check.
 - Original module
   - Found /lib/modules/4.19.42+/kernel/sound/soc/codecs/snd-soc-wm8960.ko
   - Storing in /var/lib/dkms/seeed-voicecard/original_module/4.19.42+/armv7l/
   - Archiving for uninstallation purposes
 - Installation
   - Installing to /lib/modules/4.19.42+/kernel/sound/soc/codecs/

snd-soc-ac108.ko:
Running module version sanity check.
 - Original module
   - Found /lib/modules/4.19.42+/kernel/sound/soc/codecs/snd-soc-ac108.ko
   - Storing in /var/lib/dkms/seeed-voicecard/original_module/4.19.42+/armv7l/
   - Archiving for uninstallation purposes
 - Installation
   - Installing to /lib/modules/4.19.42+/kernel/sound/soc/codecs/

snd-soc-seeed-voicecard.ko:
Running module version sanity check.
 - Original module
   - Found /lib/modules/4.19.42+/kernel/sound/soc/bcm/snd-soc-seeed-voicecard.ko
   - Storing in /var/lib/dkms/seeed-voicecard/original_module/4.19.42+/armv7l/
   - Archiving for uninstallation purposes
 - Installation
   - Installing to /lib/modules/4.19.42+/kernel/sound/soc/bcm/

depmod...

DKMS: install completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.19.42-v7+ -C /lib/modules/4.19.42-v7+/build M=/var/lib/dkms/seeed-voicecard/0.3/build.....
cleaning build area....

DKMS: build completed.

snd-soc-wm8960:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.42-v7+/kernel/sound/soc/codecs/

snd-soc-ac108.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.42-v7+/kernel/sound/soc/codecs/

snd-soc-seeed-voicecard.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.42-v7+/kernel/sound/soc/bcm/

depmod...

DKMS: install completed.
mkdir: cannot create directory ‘/etc/voicecard’: File exists
git init
Reinitialized existing Git repository in /etc/voicecard/.git/
git add --all
git commit -m "origin configures"
On branch master
nothing to commit, working tree clean

##########################################################

pi@raspberrypi:~ $ cat /var/log/seeed-voicecard.log
+ dtparam i2c_arm=on
+ modprobe i2c-dev
+ dtparam spi=on
++ i2cdetect -y 1 0x1a 0x1a
++ grep 1a
++ awk '{print $2}'
+ is_1a=1a
++ i2cdetect -y 1 0x35 0x35
++ awk '{print $2}'
++ grep 35
+ is_35=35
++ i2cdetect -y 1 0x3b 0x3b
++ awk '{print $2}'
++ grep 3b
+ is_3b=3b
+ rm /etc/asound.conf
+ rm /var/lib/alsa/asound.state
+ '[' x1a == x1a ']'
+ '[' x35 == x ']'
+ '[' x3b == x3b ']'
+ '[' x35 == x ']'
+ '[' x3b == x3b ']'
+ '[' x35 == x35 ']'
+ echo 'install 6mic'
install 6mic
+ dtoverlay seeed-8mic-voicecard
+ rm /etc/asound.conf
rm: cannot remove '/etc/asound.conf': No such file or directory
+ rm /var/lib/alsa/asound.state
rm: cannot remove '/var/lib/alsa/asound.state': No such file or directory
echo 'create 6mic asound configure file'
create 6mic asound configure file
ln -s /etc/voicecard/asound_6mic.conf /etc/asound.conf
echo 'create 6mic asound status file'
create 6mic asound status file
ln -s /etc/voicecard/ac108_6mic.state /var/lib/alsa/asound.state
alsactl restore
Found hardware: "bcm2835_alsa" "Broadcom Mixer" "" "" ""
Hardware is initialized using a generic method
alsactl: set_control:1325: failed to obtain info for control #6 (No such file or directory)
amixer cset numid=3 1
numid=3,iface=MIXER,name='PCM Playback Route'
  ; type=INTEGER,access=rw------,values=1,min=0,max=2,step=0
  : values=1

**Comment by Pillar1989** [comment] 2019-05-21 00:58
Duplicate of #159

**Closed by Pillar1989** 2019-05-21 00:58 UTC
