### ISSUE TITLE
Respeaker 2mic driver does not work on PI 3 B

### ISSUE THREAD

**Issue by dm1010111** [respeaker/seeed-voicecard#26] opened 2018-01-17 01:33 UTC
I have Raspberry Pi 3 B and hooked with respeaker 2-Mics Pi HAT.  I use Linux Rasberrypi OS 4.9.59-v7+ built on 10/29/2017. When the system up, "speaker-test -t wav" is OK.  I did following to install the 2-mics driver:
    $git clone https://github.com/respeaker/seeed-voicecard.git
    $cd seeed-voicecard
    $sudo ./install.sh 2mic
    $reboot
after system reboot, the "speaker-test -t wav" is broken.  The test 
     $ arecord -f cd -Dhw:1 | aplay -Dhw:1
Is broken. No record no playback.
Please help rootcause the issue.  It looks like "sudo ./install 2mic" 2mic driver has some issue.

**Comment by dm1010111** [comment] 2018-01-17 01:38
Add some observations:
If I use "sudo ./uninstall 2mic", then the speaker-test will work again. fro some reason, after installing 2mic driver, the on Pi 3 board speaker is disabled.

**Comment by Pillar1989** [comment] 2018-01-17 01:58
```
pi@raspberrypi:~/seeed-voicecard $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~/seeed-voicecard $ 
```
 seeed2micvoicec is   card 1 ?

**Comment by dm1010111** [comment] 2018-01-17 22:56
Hi Baozhu, on my Pi 3 and respeaker 2mic system, I can pass pass " arecord -f cd -Dhw:1 | aplay -Dhw:1"echo test.  

I got google-assistant-demo stuck.  Following is the message:
$google-assistant-demo --device_model_id 2micberry
device_model_id: 2micberry
device_id: ACDCBE4E571C34433D72A4DB1AFC502C

ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED
[2360:2386:ERROR:mic_failure_detector.cc(140)] [assistant] Channel 1 has failed. Powers -inf and -inf

$aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

$arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

I just no clue how to debug this issue.  Please let me know what is the solution.

**Comment by Pillar1989** [comment] 2018-01-18 11:32
https://github.com/respeaker/seeed-voicecard/blob/master/asound_2mic.conf#L22
https://github.com/respeaker/seeed-voicecard/blob/master/asound_2mic.conf#L29
should be "hw:1,0"

**Comment by dm1010111** [comment] 2018-01-18 21:36
Finally I resolve the issue with following .asoundrc file:
# The IPC key of dmix or dsnoop plugin must be unique
# If 555555 or 666666 is used by other processes, use another one

pcm.!default {
    type asym
    playback.pcm "playback"
    capture.pcm "capture"
}

pcm.playback {
    type plug
    slave.pcm "dmixed"
}

pcm.capture {
    type plug
    slave.pcm "array"
}

pcm.dmixed {
    type dmix
    slave.pcm "hw:1,0"
    ipc_key 555555
}

pcm.array {
    type dsnoop
    slave {
        pcm "hw:1,0"
        channels 2
    }
    ipc_key 666666
}
Thank you for all your helps, Baozhu.

**Comment by calinichta** [comment] 2018-01-20 00:05
I just updated and upgraded my Raspbian Linux Kernel to the mentioned kernel (Linux Rasberrypi OS 4.9.59-v7+) but I'm still not able to install the drivers.


"journalctl -xe" lists the following:

-- Unit systemd-modules-load.service has begun starting up.
Jan 20 00:49:30 raspberrypi systemd-modules-load[1036]: Failed to find module 'snd-soc-ac108'
Jan 20 00:49:30 raspberrypi systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
Jan 20 00:49:30 raspberrypi systemd[1]: Failed to start Load Kernel Modules.
-- Subject: Unit systemd-modules-load.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit systemd-modules-load.service has failed.
-- 
-- The result is failed.
Jan 20 00:49:30 raspberrypi systemd[1]: systemd-modules-load.service: Unit entered failed state.
Jan 20 00:49:30 raspberrypi systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
Jan 20 00:49:30 raspberrypi sudo[1030]: pam_unix(sudo:session): session closed for user root


Seems that snd-soc-ac108 is not generated, so I'm not able to see the seed2mic-device in alsamixer or somewhere else. I'm stuck since 4 hours.

Does anyone now what's wrong?

**Comment by dkmerona** [comment] 2018-01-21 00:35
have a similar problem; did sudo ./install.sh 2mic; reboot and aplay -l dont list the card

**Comment by Pillar1989** [comment] 2018-01-22 02:33
@calinichta  I think you need reflash the sd card. then reinstall the seeed-voicecard.

**Comment by dkmerona** [comment] 2018-01-22 11:08
i just boot on sd card, all my system file is on an usb without problem till now;

**Comment by calinichta** [comment] 2018-01-22 11:47
I reinstalled the image about 4 times - but on berryboot with an external
USB drive.


Setting up the latest raspbian with kernel 4.9.57 on the SD card only woks
fine.


Taking a berryboot image with kernel 4.9.57 also works fine, but not on my
time intensive and carefully installed image based on kernel 4.9.26v7-aufs.

There, the systemd complains about not finding the right drivers
snd-soc-ac108.ko and snd-soc-wm9860.ko

When I start "sudo ./install.sh" it tells me that there is no build folder
in the given kernel what is right indeed.


Does anyone got successfully build drivers for kernel 4.9.26v7-aufs in
folder "/lib/modules/4.9.26v7-aufs/kernel/sound/soc/codecs"?

Thank you very much in advance.

Am 22.01.2018 3:33 vorm. schrieb "Baozhu Zuo" <notifications@github.com>:

**Comment by Pillar1989** [comment] 2018-01-22 12:06
4.9.26v7-aufs？ we only tested seeed-voicecard on raspbian.

**Comment by calinichta** [comment] 2018-01-22 13:35
This is the raspbian image 2017-09 for berryboot with kernel 4.9.26v7-aufs -
might this cause the problem?
As I already mentioned, running an image with kernel 4.9.57 is fine.


Am 22.01.2018 1:06 nachm. schrieb "Baozhu Zuo" <notifications@github.com>:

4.9.26v7-aufs？ we only tested seeed-voicecard on raspbian.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/respeaker/seeed-voicecard/issues/26#issuecomment-359404988>,
or mute the thread

**Comment by dkmerona** [comment] 2018-01-23 19:45
for the comment on linux file, for sure its linux file because my linux system is running well for a lot of applications. typing yname -a give 4.9.59-v7

**Comment by Pillar1989** [comment] 2018-01-26 06:48
@calinichta Have you solved your issue ?

**Comment by calinichta** [comment] 2018-01-26 08:20
@Baozhu Zuo
Unfortunately I didn't have time to fix it, maybe next week...but I try hard


Am 26.01.2018 7:48 vorm. schrieb "Baozhu Zuo" <notifications@github.com>:

@calinichta <https://github.com/calinichta> Have you solved your issue ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/respeaker/seeed-voicecard/issues/26#issuecomment-360698248>,
or mute the thread

**Comment by dkmerona** [comment] 2018-01-26 19:47
i have kernel 4.9.59-v7 and it's not working. Any help?

**Comment by calinichta** [comment] 2018-01-26 20:59
I had updated to that kernel from 4.9.27 and it also didn't work, because
typing "uname -r" it still says "kernel 4.9.27...after setting up a
complete new image based on kernel 4.9.59-v7 it worked, because" uname -r"
says 4.9.59-v7.

I know that this is no help for you, but maybe you experience the same.

Am 26.01.2018 8:47 nachm. schrieb "dkmerona" <notifications@github.com>:

i have kernel 4.9.59-v7 and it's not working. Any help?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/respeaker/seeed-voicecard/issues/26#issuecomment-360886225>,
or mute the thread

**Comment by darles** [comment] 2018-01-26 23:17
Same here - not working with 4.9.26v7-aufs

**Comment by Pillar1989** [comment] 2018-01-29 01:33
@darles  @dkmerona Where can I download berryboot image ?

**Comment by calinichta** [comment] 2018-01-29 07:24
You'll find berryboot images on https://berryboot.alexgoldcheidt.com/images/


Am 29.01.2018 2:33 vorm. schrieb "Baozhu Zuo" <notifications@github.com>:

**Comment by dkmerona** [comment] 2018-01-29 19:41
anyway can we hope have a patch of driver if needed  for 4.9.59-v7 or anybody from seeed confirming that actual drivers are ok for this kernel?

**Comment by calinichta** [comment] 2018-01-29 19:45
As I already wrote, drivers work fine on an image with kernel
4.9.57-v7...but not if it was updated from 4.9.26v7-aufs.

Am 29.01.2018 8:41 nachm. schrieb "dkmerona" <notifications@github.com>:

**Comment by dkmerona** [comment] 2018-01-29 19:53
arg^^; so what to do when you are using a 4.9.57-v7; what are the steps to follow because i updated the kernel and after that i download the driver and tried to install these drivers. May be i uninstall drivers and try to install drivers once more time?

**Comment by calinichta** [comment] 2018-01-29 19:55
That didn't work for me. I had to get an image that comes with kernel
4.9.57-v7

Am 29.01.2018 8:53 nachm. schrieb "dkmerona" <notifications@github.com>:

**Comment by dkmerona** [comment] 2018-01-29 21:26
well i cannot install a new image as i have other application running ; i need a runnable driver

**Comment by Pillar1989** [comment] 2018-01-30 01:02
@dkmerona If you have raspberrypi-kernel-headers for 4.9.57-v7 version, you can ignore the new image.

**Comment by ukayzm** [comment] 2018-01-30 01:11
I'm having the same issue with the initial issue of dm1010111, but 4 mic in my case. I have Raspberry Pi 3 B, respeaker 4-Mics Pi HAT, using Raspbian stretch lite, 4.9.59-v7+ built on 10/29/2017.

Before installing 4mic driver, speaker-test -t wav works fine. After installing 4mic driver by sudo ./install.sh 4mic and reboot, speaker-test -t wav stops forever with this output on console:

```
$ speaker-test -t wav
speaker-test 1.1.3

Playback device is default
Stream parameters are 48000Hz, S16_LE, 1 channels
WAV file(s)
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 12000 to 18000
Period size range from 6000 to 6000
Using max buffer size 18000
Periods = 4
was set period_size = 6000
was set buffer_size = 18000
 0 - Front Left
```

After the above output, it does not go any more, but stops forever. I have to press ^C to get out of the stopped speaker-test. It gives this output like this when pressing ^C.

```
^CWrite error: -4,Interrupted system call
xrun_recovery failed: -4,Interrupted system call
Transfer failed: Interrupted system call
```

When I uninstall the driver by sudo ./uninstall.sh 4mic; sudo ./uninstall.sh 2mic, and reboot, speaker-test -t wav works fine. 
 I have tried this from re-installing OS several times, but the result is always same. 

The strange thing is that the recording works well, even when the playback fails. So I don't think that my 4 mic hat is physically damaged. 

Another strange thing is this log on booting up:

```
[    3.460557]  i2c_id number :0
[    3.460567]  ac108  codec_index :0
[    3.460571]  ac108  I2S data protocol type :1
[    3.461115] ac108_write error->[REG-0x00,val-0x12]
```

**Comment by ukayzm** [comment] 2018-01-30 01:19
FYI, This is the output of arecord and aplay, which is different from the one in http://wiki.seeed.cc/ReSpeaker_4_Mic_Array_for_Raspberry_Pi/ 

```
$ arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
playback
dmixed
ac108
sysdefault:CARD=seeed4micvoicec
    seeed-4mic-voicecard,
    Default Audio Device
dmix:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard,
    Direct sample mixing device
dsnoop:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard,
    Direct sample snooping device
hw:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard,
    Direct hardware device without any conversions
plughw:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard,
    Hardware device with all software conversions
$ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
playback
dmixed
ac108
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
$ 
```
Could you please review my issue? Thank you in advance.

**Comment by Pillar1989** [comment] 2018-02-01 08:19
@ukayzm we are so sorry for your encounter. We have been optimized seeed-voicecard installation scheme.  Please use the new image to install it.
`git clone https://github.com/respeaker/seeed-voicecard -b install `

**Comment by ukayzm** [comment] 2018-02-01 08:37
@Pillar1989, I re-installed driver and now it works fine. Thank you very much.

**Comment by jabulonboaz** [comment] 2018-02-07 08:49
@Pilar1989 and all you have a new image for 2mic too? Or a way to fix this issue please?
I am on a Pi3 and running AlexaPi but i can't get the the record to work. 
Even if i replace the input_device with the error log suggestions bellow then i get different errors: Error log follows:

  pi@raspberrypi:~ $ sudo systemctl status AlexaPi.service
? AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-02-07 01:35:46 UTC; 3min 56s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
  Process: 590 ExecStart=/usr/bin/python /opt/AlexaPi/src/main.py --daemon (code=exited, status=1/FAILURE)
 Main PID: 590 (code=exited, status=1/FAILURE)

Feb 07 01:35:45 raspberrypi python[590]: ALSA lib pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
Feb 07 01:35:46 raspberrypi python[590]: CRITICAL: Your input_device 'seeed-2mic-voicecard' is invalid. Use one of the following:
Feb 07 01:35:46 raspberrypi python[590]: seeed-2mic-voicecard: - (plughw:0,0)
Feb 07 01:35:46 raspberrypi python[590]: sysdefault
Feb 07 01:35:46 raspberrypi python[590]: capture
Feb 07 01:35:46 raspberrypi python[590]: array
Feb 07 01:35:46 raspberrypi python[590]: default
Feb 07 01:35:46 raspberrypi systemd[1]: AlexaPi.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 01:35:46 raspberrypi systemd[1]: AlexaPi.service: Unit entered failed state.
Feb 07 01:35:46 raspberrypi systemd[1]: AlexaPi.service: Failed with result 'exit-code'.

**Comment by Pillar1989** [comment] 2018-02-07 09:28
@jabulonboaz Please use a new raspbian image install `git clone https://github.com/respeaker/seeed-voicecard -b install` . Then setup AlexaPi to your system. install will be merge to master branch quickly.

**Comment by jabulonboaz** [comment] 2018-02-07 15:41
@Pillar1989 is this link o for the 2mic drivers yes?

**Comment by SimonGurney** [comment] 2018-02-07 18:08
I had this on a Pi Zero.

Did the following

sudo ./uninstall.sh 2mic
reboot
sudo ./uninstall.sh 4mic
reboot
sudo ./install.sh 2mic

**Comment by jabulonboaz** [comment] 2018-02-07 18:17
I tried that @SimonGurney i saw it on your other post then figured out the ".sh" missing bit from your other post.
No luck the above git link does not install it but the old .git url cloned does but i was advised to clone with this new  -b install way.
Do i have to uninstall with the hat off?
I saw u just wrote that somewhere. 
Btw my final goal is what u have to move the build on a Pi0w from the Pi3.
Any pointers are welcomed here as i been "fighting" with this thing for ages.

**Comment by SimonGurney** [comment] 2018-02-07 18:32
I did the uninstalls and installs with the hat off as it would kill my pi when I connected it.

Not sure what the new method is but I cloned with the link off the wiki which pulled the git repo.

Do you get anything?  I almost gave up hope but when I checked the button on it was working and I could see it’s state changing in python.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jabulonboaz** [comment] 2018-02-07 18:40
I am using AlexaPi and going headless no button Simon.
Are you building Alexa with AlexaPi or AVS? 
I will try your method with the normal git.

**Comment by SimonGurney** [comment] 2018-02-07 19:43
There is a button on the 2mic hat that you can read the state from via the gpio.

I’m actually just using it for audio out in a different project, also headless.  Might try the alexapi project if it gets a bit better.  Would really want drop in support before I went with it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jabulonboaz** [comment] 2018-02-07 19:43
@Pillar1989 your kind support please how do i install with just this command ?
git clone https://github.com/respeaker/seeed-voicecard -b install

**Comment by jabulonboaz** [comment] 2018-02-07 19:45
@SimonGurney so what did you use for your build?

**Comment by SimonGurney** [comment] 2018-02-07 20:38
This guide http://wiki.seeed.cc/Respeaker_2_Mics_Pi_HAT/

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jabulonboaz** [comment] 2018-02-07 22:10
@Pillar1989 

● AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-02-07 22:05:22 UTC; 1min 30s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
  Process: 562 ExecStart=/usr/bin/python /opt/AlexaPi/src/main.py --daemon (code=exited, status=1/FAILURE)
 Main PID: 562 (code=exited, status=1/FAILURE)

Feb 07 22:05:22 raspberrypi python[562]:     self.fetch_more_tokens()
Feb 07 22:05:22 raspberrypi python[562]:   File "/usr/local/lib/python2.7/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
Feb 07 22:05:22 raspberrypi python[562]:     return self.fetch_value()
Feb 07 22:05:22 raspberrypi python[562]:   File "/usr/local/lib/python2.7/dist-packages/yaml/scanner.py", line 576, in fetch_value
Feb 07 22:05:22 raspberrypi python[562]:     self.get_mark())
Feb 07 22:05:22 raspberrypi python[562]: yaml.scanner.ScannerError: mapping values are not allowed here
Feb 07 22:05:22 raspberrypi python[562]:   in "/etc/opt/AlexaPi/config.yaml", line 12, column 37
Feb 07 22:05:22 raspberrypi systemd[1]: AlexaPi.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 22:05:22 raspberrypi systemd[1]: AlexaPi.service: Unit entered failed state.
Feb 07 22:05:22 raspberrypi systemd[1]: AlexaPi.service: Failed with result 'exit-code'.

**Comment by jabulonboaz** [comment] 2018-02-07 22:43
i can hear the test sound and i can verify that recording works but alexa does not star up due to audio errors. this happens only with the Respeaker, when i do the same build with a USB mic and the audio jack of the RPi3 Alexa Pi works prefect;y. @yexiaobo-seeedstudio @Pillar1989 we need some support with details please.

**Comment by Pillar1989** [comment] 2018-02-08 00:53
@jabulonboaz  We didnt test with Alexa PI. Do you read this document https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging ? 
Alexa PI have answered the issue.
```
Feb 07 22:05:22 raspberrypi python[562]: in "/etc/opt/AlexaPi/config.yaml", line 12, column 37
```

**Comment by jabulonboaz** [comment] 2018-02-08 13:19
@Pillar1989
Yes i read it over and over and yes i have already explained that i tried all the combinations and replaced line 12 that is referring to he input device with all the combinations of names for Respeaker 2mic. What is your suggestion please ? And u still did not answer my original question on how to install your you drivers as the git URL u provided does not do anything. Your support would be highly appreciated.

**Comment by SimonGurney** [comment] 2018-02-08 13:41
Might not work but I reference the speaker card as “hw:1,0”

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jabulonboaz** [comment] 2018-02-08 13:45
Thank you @SimonGurney i will try that format. I have even tried  plughw:0,0 but i only got as far as being able to play back and record a test wav. I know respeaker works cuz i used it with another git than AlexaPi which  was AssistantsPi but there is some issue here with the naming of the Respeaker. 
Will give your suggestion a go and report back mate cheers.

**Comment by jabulonboaz** [comment] 2018-02-08 20:10
"hw:0,0" did not work.

@Pillar1989 @yexiaobo-seeedstudio  @anyone that can help please.
This in the URL link bellow please find the detailed debug information, i cant get this to work :(

Your ALSA information is located at http://www.alsa-project.org/db/?f=37022a4253e49bbbc09120eb9411cbe71b51c9f8

pi@raspberrypi:~ $ cd ~ && wget https://raw.githubusercontent.com/alexa-pi/AlexaPi-misc/master/alsa-info.sh && bash alsa-info.sh
--2018-02-08 20:07:28--  https://raw.githubusercontent.com/alexa-pi/AlexaPi-misc/master/alsa-info.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.60.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.60.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27872 (27K) [text/plain]
Saving to: ‘alsa-info.sh.1’

alsa-info.sh.1      100%[===================>]  27.22K  --.-KB/s    in 0.03s

2018-02-08 20:07:29 (865 KB/s) - ‘alsa-info.sh.1’ saved [27872/27872]

ALSA Information Script v 0.4.64
--------------------------------

This script visits the following commands/files to collect diagnostic
information about your ALSA installation and sound related hardware.

  dmesg
  lspci
  lsmod
  aplay
  amixer
  alsactl
  /proc/asound/
  /sys/class/sound/
  ~/.asoundrc (etc.)

See 'alsa-info.sh --help' for command line options.

cat: '/sys/module/snd_soc_simple_card/parameters/*': No such file or directory
Automatically upload ALSA information to www.alsa-project.org? [y/N] : y
Uploading information to www.alsa-project.org ...  Done!

Your ALSA information is located at http://www.alsa-project.org/db/?f=37022a4253e49bbbc09120eb9411cbe71b51c9f8

**Comment by SimonGurney** [comment] 2018-02-08 21:01
How about “hw:1,0”

**Comment by jabulonboaz** [comment] 2018-02-08 21:18
@SimonGurney show me your aplay -l please.  your cardmust be =1 that is why hw:1,0 works for ypu but my card is at 0 and my device is at 0 as you can see from my debug file.

Why should i try hw:1,0 ?

**Comment by SimonGurney** [comment] 2018-02-08 22:27
Yes you’re right, hdmi is my 0 card

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SimonGurney** [comment] 2018-02-08 23:51
Nice, do you know if it supports drop in calls?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jabulonboaz** [comment] 2018-02-09 00:04
I will test it and report back Simon. For sure it supports music streaming from tunein and controls my smarthome devices.

**Comment by jabulonboaz** [comment] 2018-02-09 02:03
I still like to know how to do it in assistant pi too though. The respeaker works no drought the issue is how to make it work with AlexaPi.

**Comment by Pillar1989** [comment] 2018-02-09 03:45
@jabulonboaz 
The squeaking wheel gets the oil. 
You win. 
That's page for you. https://github.com/respeaker/seeed-voicecard/wiki/AlexaPi

**Comment by jabulonboaz** [comment] 2018-02-09 08:39
@Pillar1989 WOW! you fixed it  i will try it immediately!!  
One question it will work on the latest Raspbian jassie lite OS - (no desktop GUI) right?  
Thank you!

**Closed** 2018-02-09 09:41 UTC

**Comment by jabulonboaz** [comment] 2018-02-09 15:30
"tutorial for nincompoop" that a bit rood mate... 
Again @Pillar1989 like i mentioned to you in different streams thank you for trying but the new build command does not build anything.

pi@raspberrypi:~ $ arecord -f cd | aplay
arecord: main:788: audio open error: No such file or directory
aplay: playback:2787: read error
pi@raspberrypi:~ $

I followed your new guide to the letter:

"git clone https://github.com/respeaker/seeed-voicecard -b install
cd seeed-voicecard/
pi@raspberrypi:~/seeed-voicecard $ sudo ./install.sh "

pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
Subdevices: 8/8
Subdevice #0: subdevice #0
Subdevice #1: subdevice #1
Subdevice #2: subdevice #2
Subdevice #3: subdevice #3
Subdevice #4: subdevice #4
Subdevice #5: subdevice #5
Subdevice #6: subdevice #6
Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
Subdevices: 1/1
Subdevice #0: subdevice #0

is this suppose to run on Raspbian stretch with desktop only? I m on Raspbian Jessie lite. DO i need to install a specific version of python maybe?

**Comment by Pillar1989** [comment] 2018-02-09 23:39
Please login gitter at Beijing time 10 in the morning. I will teach you how to do this.

**Comment by dkmerona** [comment] 2018-02-25 14:23
Well. Coming back hoping thinks Evolved but still install not OK.
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

Whe following the guide to the letter (^^) i get the following error message 👍 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/30391054/36642430-9cdb5a3a-1a3f-11e8-8443-0ffb42b51273.png">
<img width="597" alt="image" src="https://user-images.githubusercontent.com/30391054/36642433-a41d31ec-1a3f-11e8-9f39-1b8190a17864.png">


i've tried the --force command but same result and aplay -l give 👍 
aplay -l
**** Liste des Périphériques Matériels PLAYBACK ****
carte 0: ALSA [bcm2835 ALSA], périphérique 0: bcm2835 ALSA [bcm2835 ALSA]
  Sous-périphériques: 8/8
  Sous-périphérique #0: subdevice #0
  Sous-périphérique #1: subdevice #1
  Sous-périphérique #2: subdevice #2
  Sous-périphérique #3: subdevice #3
  Sous-périphérique #4: subdevice #4
  Sous-périphérique #5: subdevice #5
  Sous-périphérique #6: subdevice #6
  Sous-périphérique #7: subdevice #7
carte 0: ALSA [bcm2835 ALSA], périphérique 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0


Well what a weird product!!

**Comment by jabulonboaz** [comment] 2018-02-26 04:15
execute raspi-config [you need sudo for this]
-Go to Interfacing options Enable SPI
-Reboot

**Comment by jabulonboaz** [comment] 2018-02-26 04:17
I solved it by installing the i2c-tools package and restarting the voicecard service as follows:
sudo apt-get install i2c-tools
I did this because the status of the voicecard service hinted at the use of i2cdetect, which it couldn't find as it wasn't installed. Then restarting the service:
sudo systemctl restart seeed-voicecard
Recording seems to be perfect now.

**Comment by dkmerona** [comment] 2018-03-02 23:12
its not helping; SPI was enabled and i2c-Tools is installed. I Wonder if i dont have a problem because i am powering the card through usb port. May try next time to just power by putting the card over the pi

**Comment by mario-dureso** [comment] 2020-05-16 08:17
Hello,
  Old post but same problem for me today : 
I can't use Seeed Respeaker 2-MIC HAT Card on Raspberry PI 3B+ witch Berryboot (berryboot-20190612-pi0-pi1-pi2-pi3) / Raspbian Buster ( 2019-10.img192)
No error when installing driver but message on boot :
[...]
"Failed to start Load Kernel Modules"
[...]
"Failed to start Load Kernel Modules"
[...]
"Failed to start Seeed Voice-card services"
[...]

Can Seeed help us to install driver with berryboot kernel 
pi@raspberrypi:~ $ uname -r
4.19.49v6v7-aufs

Thanks for your help.

**Comment by manekinekko** [comment] 2020-12-18 22:54
I am having the same issue with kernel `5.4.79-v7+`. Unable to use the Respeaker 2-MIC HAT Card on Raspberry PI 3B+.
