### ISSUE TITLE
Use Seeed Respeaker on Another Pi Hardware

### ISSUE THREAD

**Issue by mzprz** [respeaker/seeed-voicecard#270] opened 2020-12-08 09:05 UTC
Hi, I'm a noob and was wondering if it's possible to use Respeaker Mic Array on another pi device (e.g. Nanopi M4 with Lubuntu/FriendlyArm dist) due to the similarity on its GPIO pins. If so, what procedure I must modify from the existing install script? Any kind of insight would be appreciated, thanks a lot!

**Comment by AIWintermuteAI** [comment] 2021-07-23 02:00
Hello!
Consult README for list of officially supported platforms.
This seems to be a general question not a bug/feature request. It is better to be addressed in Seeed Forum reSpeaker subforum.
https://forum.seeedstudio.com/c/products/respeaker/15

**Closed by AIWintermuteAI** 2021-07-23 02:00 UTC
