### ISSUE TITLE
(Grove GP12) I2S Microphone

### ISSUE THREAD

**Issue by SebAcou** [respeaker/seeed-voicecard#303] opened 2021-07-12 14:43 UTC
Hello, 
I would like to add a PDM microphone (plugged on the the GP12 grove port). Is there build-in libraries or ressources on how to read the signal from this port?
Best Regards

**Comment by AIWintermuteAI** [comment] 2021-07-23 02:02
Hello!
This seems to be a general question not a bug/feature request. It is better to be addressed in Seeed Forum reSpeaker subforum.
https://forum.seeedstudio.com/c/products/respeaker/15

**Closed by AIWintermuteAI** 2021-07-23 02:02 UTC
