### ISSUE TITLE
Why seeed-voice-card driver?

### ISSUE THREAD

**Issue by shawaj** [respeaker/seeed-voicecard#279] opened 2021-01-02 14:27 UTC
Is there a reason why in the 2 mic version you are using the `simple-audio-card` driver but in the 4 and 6 mic versions you are using the custom `seeed-voice-card` instead?

I'm trying to add support for your boards to the mainline kernel and want to understand why you have changed this and if it is really necessary?

**Comment by HinTak** [comment] 2021-01-02 18:03
You mean kernel 5.9 ? See https://github.com/HinTak/seeed-voicecard/tree/v5.9 . 5.10 was out a few days ago, I haven't looked at it yet.

The 2-mics device has different hardware compared to the others; but as far as I remember it also uses the custom seeed voice card driver, although it can be used with simple-audio-card -based driver from elsewhere also.

**Comment by shawaj** [comment] 2021-01-02 18:15
What I mean is, in the [device tree overlay](seeed-2mic-voicecard-overlay.dts) for the 2 mic version it uses simple-audio-card.

But in the [4 mic]() and [6 mic]() it uses seeed-voice-card.

I wondered why it wasn't using simple-audio-card and whether it would be compatible?

**Comment by shawaj** [comment] 2021-01-02 18:27
@HinTak basically I'm trying to add the overlay support directly to RasPi OS without needing install script like it is now, to make it quicker and easier for users https://github.com/raspberrypi/linux/pull/4039

**Comment by HinTak** [comment] 2021-01-02 19:11
You cannot - see licensing issue I commented on at https://github.com/respeaker/seeed-voicecard/issues/213

**Comment by shawaj** [comment] 2021-01-02 20:40
https://github.com/respeaker/seeed-voicecard/blob/v5.5/ac101.c

It has details for people from allwinner and seeed.

It doesn't seem to be an issue.

Also I think it can go into Raspberry Pi kernel it doesn't necessarily need to go all the way upstream...

**Comment by shawaj** [comment] 2021-01-02 20:49
Also @HinTak the domain name works and redirects to allwinner www.reuuimllatech.com

**Comment by HinTak** [comment] 2021-01-03 03:30
http://www.reuuimllatech.com/ is somebody's idea of a joke - since allwinner people decided to hid their identity by spelling their company name backwards, the way site also shows their web site backward (with the right browser).

Anyway, you don't have to convince me that the copyright allows upstreaming - you need to convince the upstream people (which ever you mean). And from my experience, good luck. 

And I am speaking as somebody who have successfully upstream code into the Linux kernel in the past, as well as a person who reviewed (and would have certainly rejected such copyright-dubious...) submitted code.

**Comment by shawaj** [comment] 2021-01-03 09:33
@HinTak it is a 302 redirect straight to allwinner ```
Result
http://www.reuuimllatech.com/
301 Moved Permanently
https://www.reuuimllatech.com/
302 Found
https://www.allwinnertech.com/
200 OK
```

**Comment by HinTak** [comment] 2021-01-03 11:29
You don't need to convince me. Good luck upstreaming.

**Comment by shawaj** [comment] 2021-01-03 11:47
@HinTak thanks.

And back to my original question, is there a reason they're not just using simple-audio-card and have created their own version?

**Comment by HinTak** [comment] 2021-01-03 22:56
It was based on simple-audio-card, then diverged. You can check the repository's history, back to about 2017, I think.

**Comment by HinTak** [comment] 2021-01-03 22:58
April 2018 - https://github.com/respeaker/seeed-voicecard/commit/d0d9107c912893676405bcd27dba692b886a87cb

**Comment by shawaj** [comment] 2021-01-16 02:06
Thanks @HinTak so I guess in principle it will work with simple-audio-card assuming the codec drivers are available

**Comment by HinTak** [comment] 2021-01-16 12:02
@shawaj I think you likely guess wrong, but you are welcomed to try to fix 2 years of divergence... :)

**Comment by shawaj** [comment] 2021-01-16 18:28
It worked 2 years ago, and still works with those old drivers. So seems like it is fine to me

**Comment by HinTak** [comment] 2021-01-16 22:47
@shawaj against 4.10 or 3.x kernel, two years ago. Good luck doing it for 5.x . 

You seem to think that simple-audio-card has not changed - sorry to disappoint you, but the divergence is largely at the upstream's side: the Linux kernel audio stack / RaspberryPi people have re-arranged the simple-audio-card code about 5-6 times at least. My branches are largely just to keep up with upstream's changes; so my branches are closer to upstream than seeed-studio's. And that's already a lot of hard work.

As I said, good luck trying.

**Comment by shawaj** [comment] 2021-01-16 22:57
Your fork seems to be using the seeed-voice-card not the simple-audio-card? So not really understanding your meaning.

Your work is great, and I think probably many people appreciate it very much (me included!), but I think having it in the mainline pi kernel, and meaning that this is maintained by a wider pool of people is probably long term a better solution especially for quite common chip like wm8960. And makes it easier for users.

For the X power ones I guess not as common but same applies, assuming codec can be included in Pi mainline.

Anyway, just my opinion, sounds like you probably disagree :-)

**Comment by HinTak** [comment] 2021-01-17 06:59
Seeed-voice-card is how simple-audio-card was like back in early 4.x. Upstream simple audio card changes every 2/3 kernel minor versions, so that's about a dozen incompatible changes. For in-tree drivers they get updated when these things happens.

Anyway, it is a chicken-and-egg problem - if seeed-voice-card becomes more **current** simple-audio-card like, it becomes easier to catch-up... But you need to catch up to make it more **current** audio-card like.

And that's aside from the X power licensing issue - it is rather frown upon to submit code you did not write, and of a quality you cannot guarantee... And the technical issue like #251 which destabilizes the whole system... I have spent enough time on it and I prefer not to :-( .

**Comment by AIWintermuteAI** [comment] 2021-07-23 02:00
Hello!
This seems to be a general question not a bug/feature request. It is better to be addressed in Seeed Forum reSpeaker subforum.
https://forum.seeedstudio.com/c/products/respeaker/15

**Closed by AIWintermuteAI** 2021-07-23 02:00 UTC
Labels: no-issue-activity
